// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:logosophy/providers/books/book_model.dart';
import 'package:logosophy/providers/search_history/history_model.dart';
import 'package:logosophy/providers/search_history/search_model.dart';
import 'package:logosophy/providers/settings/settings_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BookDataAdapter());
    registerAdapter(HistoryAdapter());
    registerAdapter(SearchResultAdapter());
    registerAdapter(SettingsAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BookDataAdapter());
    registerAdapter(HistoryAdapter());
    registerAdapter(SearchResultAdapter());
    registerAdapter(SettingsAdapter());
  }
}
